list_1=[0,1,2,3,4,5,6,7,8,9]
print('第一题：将上列数组进行翻转\n')
list_1.reverse()
print(list_1)
print('*'*50)
print('第二题：将翻转后的数组拼接成字符串\n')
list_2=[]
for i in list_1:
    list_2.append(str(i))
print(list_2)
str_1=''.join(list_2)
print(str_1)
print('*'*50)
print('第三题：用字符串的切片方式取出第三到第八个字符\n')
take3_8=str_1[2:8]
print(take3_8)
print('*'*50)
print('第四题：将获得的字符串进行翻转\n')
flip=take3_8[::-1]      #该句型还不是很明白，后续需要了解了解
print(flip)
print('*'*50)
int_num=int(flip)
print('转换为int:\n',int_num)
print('*'*50)
print('转换为二进制：\n',bin(int_num))
print('*'*50)
print('转换为八进制:\n',oct(int_num))
print('*'*50)
print('转换为十六进制：\n',hex(int_num))