number_1=float(input('Enter your first number: '))
number_2=float(input('Enter your second number: '))
print('{}+{}='.format(number_1, number_2))
print(number_1+number_2)
print('{}-{}='.format(number_1, number_2))
print(number_1-number_2)
print('{}*{}='.format(number_1, number_2))
print(number_1*number_2)
print('{}/{}='.format(number_1, number_2))
print(number_1/number_2)